server:
  port: 8092

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://localhost:8090/uaa/token_keys
    client:
      client-id: address
      client-secret: secret
      access-token-uri: http://localhost:8090/uaa/oauth/token
      scope: address.validate

oauth2:
  resource:
    address-uri: http://localhost:8093/api/v1/addresses/validate