server:
  port: 8093

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://localhost:8090/uaa/token_keys